name: Build

on: [push]

jobs:
  validate-dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: yarn validate:dependencies
      run: |
        yarn install
        yarn validate:dependencies
  build-linux:
    runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: yarn install
      run: yarn install
#     - name: yarn test
#       run: |
#         yarn lint || true # TODO - temporary disable
#         yarn test
    - name: yarn build
      run: yarn build-linux
    - uses: actions/upload-artifact@master
      with:
        name: scanner-linux
        path: dist/scanner
